### ISSUE TITLE
Furnace misses line of pixels on the top left

### ISSUE THREAD

**Issue by antifreak** [JosefLitos/Enhanced-Faithcraft#3]
The top line of one of the sides of the furnace texture is missing. This is without having any other ressourcepacks active.

https://ibb.co/G087736

Thank you for your work

**Comment by litoj** [comment]
Hi, which version are you on? I fixed it immediately. However, since the rename of `grass` to `short_grass` the resourcepack has also some files renamed.

Anyways, here is the fix for 1.20.4 and above:

[EF_Heavy_1.20.4+.zip](https://github.com/user-attachments/files/18281061/EF_Heavy_1.20.4%2B.zip)
